/**
 *
 *  ******************************************************************************
 *  MontiCAR Modeling Family, www.se-rwth.de
 *  Copyright (c) 2017, Software Engineering Group at RWTH Aachen,
 *  All rights reserved.
 *
 *  This project is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 3.0 of the License, or (at your option) any later version.
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this project. If not, see <http://www.gnu.org/licenses/>.
 * *******************************************************************************
 */
/* generated by template symboltable.ScopeSpanningSymbol*/


package de.monticore.lang.monticar.cnnarch._symboltable;

import de.monticore.lang.monticar.cnnarch.PredefinedVariables;
import de.monticore.symboltable.CommonScopeSpanningSymbol;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.function.BiFunction;

public class MethodDeclarationSymbol extends CommonScopeSpanningSymbol {

    public static final MethodDeclarationKind KIND = new MethodDeclarationKind();

    private List<VariableSymbol> parameters;
    private CompositeLayerSymbol body;
    private BiFunction<List<ShapeSymbol>, MethodLayerSymbol, List<ShapeSymbol>> shapeFunction = null;

    protected MethodDeclarationSymbol(String name) {
        super(name, KIND);
    }

    @Override
    protected MethodDeclarationScope createSpannedScope() {
        return new MethodDeclarationScope();
    }

    public List<VariableSymbol> getParameters() {
        return parameters;
    }

    protected void setParameters(List<VariableSymbol> parameters) {
        this.parameters = parameters;
        if (!getParameter(PredefinedVariables.IF_NAME).isPresent()){
            VariableSymbol ifParam = PredefinedVariables.createIfParameter();
            getSpannedScope().getAsMutableScope().add(ifParam);
            this.parameters.add(ifParam);
        }
        if (!getParameter(PredefinedVariables.FOR_NAME).isPresent()){
            VariableSymbol forParam = PredefinedVariables.createForParameter();
            getSpannedScope().getAsMutableScope().add(forParam);
            this.parameters.add(forParam);
        }
    }

    public CompositeLayerSymbol getBody() {
        return body;
    }

    protected void setBody(CompositeLayerSymbol body) {
        this.body = body;
    }

    public boolean isPredefined() {
        return shapeFunction != null;
    }

    public BiFunction<List<ShapeSymbol>, MethodLayerSymbol, List<ShapeSymbol>> getShapeFunction() {
        return shapeFunction;
    }

    protected void setShapeFunction(BiFunction<List<ShapeSymbol>, MethodLayerSymbol, List<ShapeSymbol>> shapeFunction) {
        this.shapeFunction = shapeFunction;
    }

    public Optional<VariableSymbol> getParameter(String name) {
        Optional<VariableSymbol> res = Optional.empty();
        for (VariableSymbol parameter : getParameters()){
            if (parameter.getName().equals(name)){
                res = Optional.of(parameter);
            }
        }
        return res;
    }


    public void call(MethodLayerSymbol layer) {
        if (layer.getParallelLength() == 1 && layer.getSerialLength() == 1){
            if (isPredefined()){
                layer.setResolvedThis(layer);
            }
            else {
                for (VariableSymbol param : getParameters()){
                    param.reset();
                }
                for (ArgumentSymbol arg : layer.getArguments()){
                    arg.set();
                }
                LayerSymbol bodyCopy = getBody().copy();
                layer.setResolvedThis(bodyCopy);
                bodyCopy.resolve();
            }
        }
    }


    public static class Builder{
        private List<VariableSymbol> parameters = new ArrayList<>();
        private CompositeLayerSymbol body;
        private String name = "";
        private BiFunction<List<ShapeSymbol>, MethodLayerSymbol, List<ShapeSymbol>> shapeFunction = (inputShape, method) -> inputShape;

        public Builder parameters(List<VariableSymbol> parameters) {
            this.parameters = parameters;
            return this;
        }

        public Builder parameters(VariableSymbol... parameters) {
            this.parameters = new ArrayList<>(Arrays.asList(parameters));
            return this;
        }

        public Builder body(CompositeLayerSymbol body) {
            this.body = body;
            return this;
        }

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public Builder shapeFunction(BiFunction<List<ShapeSymbol>, MethodLayerSymbol, List<ShapeSymbol>> shapeFunction){
            this.shapeFunction = shapeFunction;
            return this;
        }

        public MethodDeclarationSymbol build(){
            if (name == null || name.equals("")){
                throw new IllegalStateException("Missing or empty name for MethodDeclarationSymbol");
            }
            MethodDeclarationSymbol sym = new MethodDeclarationSymbol(name);
            sym.setBody(body);
            sym.setParameters(parameters);
            sym.setShapeFunction(shapeFunction);
            return sym;
        }
    }
}
